import { z } from 'zod';

export const MenuItemSchema = z.object({
  id: z.string().min(1),
  original_name: z.string().default(''),
  translated_name: z.string().default(''),
  description: z.string().default(''),
  price: z.string().default(''),
  notes: z.string().default(''),
});

export const MenuSectionSchema = z.object({
  id: z.string().min(1),
  title: z.string().default(''),
  items: z.array(MenuItemSchema),
});

export const TranslateMenuResultSchema = z.object({
  restaurant_name: z.string().default(''),
  recognition_status: z.enum(['recognized', 'uncertain', 'unable_to_recognize']),
  partial_menu_notice: z.string().default(''),
  sections: z.array(MenuSectionSchema),
});

export type TranslateMenuResult = z.infer<typeof TranslateMenuResultSchema>;

export const DishExploreResultSchema = z.object({
  englishName: z.string().default(''),
  chineseName: z.string().default(''),
  pinyin: z.string().default(''),
  shortDescription: z.string().default(''),
  origin: z.string().default(''),
  mainIngredients: z.array(z.string()).default([]),
  flavorProfile: z.array(z.string()).default([]),
  spiceLevel: z.enum(['Not spicy', 'Mild', 'Medium', 'Spicy', 'Very spicy']),
  commonAllergens: z.array(z.string()).default([]),
  dietaryNotes: z.array(z.string()).default([]),
  howItIsServed: z.string().default(''),
  howToEat: z.string().default(''),
  portionGuide: z.string().default(''),
  beginnerFriendly: z.boolean(),
  orderingPhraseChinese: z.string().default(''),
  orderingPhrasePinyin: z.string().default(''),
  orderingPhraseEnglish: z.string().default(''),
  recognitionStatus: z.enum(['recognized', 'uncertain', 'unable_to_confirm']),
});

export type DishExploreResult = z.infer<typeof DishExploreResultSchema>;

export const ProductUnderstandResultSchema = z.object({
  recognitionStatus: z.enum(['recognized', 'uncertain', 'unable_to_recognize']),
  productName: z.string().default(''),
  originalName: z.string().default(''),
  category: z.enum(['food', 'drink', 'medicine', 'skincare', 'cosmetics', 'daily_goods', 'souvenir', 'unknown']),
  description: z.string().default(''),
  ingredients: z.array(z.string()).default([]),
  allergens: z.array(z.string()).default([]),
  warnings: z.array(z.string()).default([]),
  goodFor: z.array(z.string()).default([]),
  flavor: z.string().default(''),
  sugar: z.string().default(''),
  caffeine: z.string().default(''),
  alcohol: z.string().default(''),
  whatItIs: z.string().default(''),
  howToUse: z.string().default(''),
  whatItDoes: z.string().default(''),
  skinType: z.string().default(''),
  keyIngredients: z.array(z.string()).default([]),
  notes: z.array(z.string()).default([]),
  confidence: z.enum(['high', 'medium', 'low']),
  needsManualCheck: z.boolean(),
});

export type ProductUnderstandResult = z.infer<typeof ProductUnderstandResultSchema>;

export const AddressInputTypeSchema = z.enum([
  'chinese_address',
  'english_address',
  'chinese_place_name',
  'english_place_name',
  'mixed',
  'unknown',
]);

export const ParsedAddressSchema = z.object({
  country: z.string().optional(),
  province: z.string().optional(),
  municipality: z.string().optional(),
  city: z.string().optional(),
  district: z.string().optional(),
  county: z.string().optional(),
  town: z.string().optional(),
  subdistrict: z.string().optional(),
  road: z.string().optional(),
  roadDirection: z.string().optional(),
  roadNumber: z.string().optional(),
  lane: z.string().optional(),
  alley: z.string().optional(),
  building: z.string().optional(),
  buildingNumber: z.string().optional(),
  unit: z.string().optional(),
  floor: z.string().optional(),
  room: z.string().optional(),
  landmark: z.string().optional(),
  placeName: z.string().optional(),
  entrance: z.string().optional(),
  gate: z.string().optional(),
  nearbyReference: z.string().optional(),
});

export const AddressTranslationResultSchema = z.object({
  inputType: AddressInputTypeSchema,
  detectedLanguage: z.enum(['zh', 'en', 'mixed', 'unknown']),
  originalInput: z.string().default(''),
  chineseAddress: z.string().default(''),
  englishAddress: z.string().default(''),
  shortChineseLabel: z.string().default(''),
  shortEnglishLabel: z.string().default(''),
  parsedAddress: ParsedAddressSchema.default({}),
  confidence: z.enum(['high', 'medium', 'low']),
  isAmbiguous: z.boolean(),
  needsMoreInformation: z.boolean(),
  missingInformation: z.array(z.string()).default([]),
  ambiguityMessage: z.string().default(''),
  formattingNotes: z.array(z.string()).default([]),
  verificationStatus: z.literal('not_verified'),
  driverCard: z.object({
    destinationChinese: z.string().default(''),
    destinationEnglish: z.string().default(''),
    instructionChinese: z.string().default('请带我去这个地址。'),
    instructionEnglish: z.string().default('Please take me to this address.'),
  }),
});

export type AddressTranslationResult = z.infer<typeof AddressTranslationResultSchema>;

export const RailTicketResultSchema = z.object({
  recognitionStatus: z.enum(['recognized', 'uncertain', 'unable_to_recognize']),
  sourceType: z.enum(['12306', 'trip_com', 'china_railway_e_ticket', 'order_screenshot', 'unknown']),
  trainNumber: z.string().default(''),
  fromStation: z.string().default(''),
  fromStationEnglish: z.string().default(''),
  toStation: z.string().default(''),
  toStationEnglish: z.string().default(''),
  departureDate: z.string().default(''),
  departureTime: z.string().default(''),
  arrivalDate: z.string().default(''),
  arrivalTime: z.string().default(''),
  carriage: z.string().default(''),
  seat: z.string().default(''),
  seatClass: z.string().default(''),
  passengerName: z.string().default(''),
  boardingGate: z.string().default(''),
  boardingGateEnglish: z.string().default(''),
  waitingHall: z.string().default(''),
  waitingHallEnglish: z.string().default(''),
  platform: z.string().default(''),
  platformEnglish: z.string().default(''),
  gate: z.string().default(''),
  gateEnglish: z.string().default(''),
  checkIn: z.string().default(''),
  checkInEnglish: z.string().default(''),
  coach: z.string().default(''),
  ticketNumber: z.string().default(''),
  orderNumber: z.string().default(''),
  notes: z.array(z.string()).default([]),
  confidence: z.enum(['high', 'medium', 'low']),
  needsManualCheck: z.boolean(),
});

export type RailTicketResult = z.infer<typeof RailTicketResultSchema>;

export const translateMenuJsonSchema = {
  type: 'object',
  additionalProperties: false,
  required: ['restaurant_name', 'recognition_status', 'partial_menu_notice', 'sections'],
  properties: {
    restaurant_name: { type: 'string' },
    recognition_status: {
      type: 'string',
      enum: ['recognized', 'uncertain', 'unable_to_recognize'],
    },
    partial_menu_notice: { type: 'string' },
    sections: {
      type: 'array',
      items: {
        type: 'object',
        additionalProperties: false,
        required: ['id', 'title', 'items'],
        properties: {
          id: { type: 'string' },
          title: { type: 'string' },
          items: {
            type: 'array',
            items: {
              type: 'object',
              additionalProperties: false,
              required: [
                'id',
                'original_name',
                'translated_name',
                'description',
                'price',
                'notes',
              ],
              properties: {
                id: { type: 'string' },
                original_name: { type: 'string' },
                translated_name: { type: 'string' },
                description: { type: 'string' },
                price: { type: 'string' },
                notes: { type: 'string' },
              },
            },
          },
        },
      },
    },
  },
} as const;

export const productUnderstandJsonSchema = {
  type: 'object',
  additionalProperties: false,
  required: [
    'recognitionStatus',
    'productName',
    'originalName',
    'category',
    'description',
    'ingredients',
    'allergens',
    'warnings',
    'goodFor',
    'flavor',
    'sugar',
    'caffeine',
    'alcohol',
    'whatItIs',
    'howToUse',
    'whatItDoes',
    'skinType',
    'keyIngredients',
    'notes',
    'confidence',
    'needsManualCheck',
  ],
  properties: {
    recognitionStatus: { type: 'string', enum: ['recognized', 'uncertain', 'unable_to_recognize'] },
    productName: { type: 'string' },
    originalName: { type: 'string' },
    category: { type: 'string', enum: ['food', 'drink', 'medicine', 'skincare', 'cosmetics', 'daily_goods', 'souvenir', 'unknown'] },
    description: { type: 'string' },
    ingredients: { type: 'array', items: { type: 'string' } },
    allergens: { type: 'array', items: { type: 'string' } },
    warnings: { type: 'array', items: { type: 'string' } },
    goodFor: { type: 'array', items: { type: 'string' } },
    flavor: { type: 'string' },
    sugar: { type: 'string' },
    caffeine: { type: 'string' },
    alcohol: { type: 'string' },
    whatItIs: { type: 'string' },
    howToUse: { type: 'string' },
    whatItDoes: { type: 'string' },
    skinType: { type: 'string' },
    keyIngredients: { type: 'array', items: { type: 'string' } },
    notes: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'string', enum: ['high', 'medium', 'low'] },
    needsManualCheck: { type: 'boolean' },
  },
} as const;

export const dishExploreJsonSchema = {
  type: 'object',
  additionalProperties: false,
  required: [
    'englishName',
    'chineseName',
    'pinyin',
    'shortDescription',
    'origin',
    'mainIngredients',
    'flavorProfile',
    'spiceLevel',
    'commonAllergens',
    'dietaryNotes',
    'howItIsServed',
    'howToEat',
    'portionGuide',
    'beginnerFriendly',
    'orderingPhraseChinese',
    'orderingPhrasePinyin',
    'orderingPhraseEnglish',
    'recognitionStatus',
  ],
  properties: {
    englishName: { type: 'string' },
    chineseName: { type: 'string' },
    pinyin: { type: 'string' },
    shortDescription: { type: 'string' },
    origin: { type: 'string' },
    mainIngredients: { type: 'array', items: { type: 'string' } },
    flavorProfile: { type: 'array', items: { type: 'string' } },
    spiceLevel: {
      type: 'string',
      enum: ['Not spicy', 'Mild', 'Medium', 'Spicy', 'Very spicy'],
    },
    commonAllergens: { type: 'array', items: { type: 'string' } },
    dietaryNotes: { type: 'array', items: { type: 'string' } },
    howItIsServed: { type: 'string' },
    howToEat: { type: 'string' },
    portionGuide: { type: 'string' },
    beginnerFriendly: { type: 'boolean' },
    orderingPhraseChinese: { type: 'string' },
    orderingPhrasePinyin: { type: 'string' },
    orderingPhraseEnglish: { type: 'string' },
    recognitionStatus: {
      type: 'string',
      enum: ['recognized', 'uncertain', 'unable_to_confirm'],
    },
  },
} as const;

export const addressTranslationJsonSchema = {
  type: 'object',
  additionalProperties: false,
  required: [
    'inputType',
    'detectedLanguage',
    'originalInput',
    'chineseAddress',
    'englishAddress',
    'shortChineseLabel',
    'shortEnglishLabel',
    'parsedAddress',
    'confidence',
    'isAmbiguous',
    'needsMoreInformation',
    'missingInformation',
    'ambiguityMessage',
    'formattingNotes',
    'verificationStatus',
    'driverCard',
  ],
  properties: {
    inputType: {
      type: 'string',
      enum: ['chinese_address', 'english_address', 'chinese_place_name', 'english_place_name', 'mixed', 'unknown'],
    },
    detectedLanguage: { type: 'string', enum: ['zh', 'en', 'mixed', 'unknown'] },
    originalInput: { type: 'string' },
    chineseAddress: { type: 'string' },
    englishAddress: { type: 'string' },
    shortChineseLabel: { type: 'string' },
    shortEnglishLabel: { type: 'string' },
    parsedAddress: {
      type: 'object',
      additionalProperties: false,
      required: [
        'country',
        'province',
        'municipality',
        'city',
        'district',
        'county',
        'town',
        'subdistrict',
        'road',
        'roadDirection',
        'roadNumber',
        'lane',
        'alley',
        'building',
        'buildingNumber',
        'unit',
        'floor',
        'room',
        'landmark',
        'placeName',
        'entrance',
        'gate',
        'nearbyReference',
      ],
      properties: {
        country: { type: 'string' },
        province: { type: 'string' },
        municipality: { type: 'string' },
        city: { type: 'string' },
        district: { type: 'string' },
        county: { type: 'string' },
        town: { type: 'string' },
        subdistrict: { type: 'string' },
        road: { type: 'string' },
        roadDirection: { type: 'string' },
        roadNumber: { type: 'string' },
        lane: { type: 'string' },
        alley: { type: 'string' },
        building: { type: 'string' },
        buildingNumber: { type: 'string' },
        unit: { type: 'string' },
        floor: { type: 'string' },
        room: { type: 'string' },
        landmark: { type: 'string' },
        placeName: { type: 'string' },
        entrance: { type: 'string' },
        gate: { type: 'string' },
        nearbyReference: { type: 'string' },
      },
    },
    confidence: { type: 'string', enum: ['high', 'medium', 'low'] },
    isAmbiguous: { type: 'boolean' },
    needsMoreInformation: { type: 'boolean' },
    missingInformation: { type: 'array', items: { type: 'string' } },
    ambiguityMessage: { type: 'string' },
    formattingNotes: { type: 'array', items: { type: 'string' } },
    verificationStatus: { type: 'string', enum: ['not_verified'] },
    driverCard: {
      type: 'object',
      additionalProperties: false,
      required: ['destinationChinese', 'destinationEnglish', 'instructionChinese', 'instructionEnglish'],
      properties: {
        destinationChinese: { type: 'string' },
        destinationEnglish: { type: 'string' },
        instructionChinese: { type: 'string' },
        instructionEnglish: { type: 'string' },
      },
    },
  },
} as const;

export const railTicketJsonSchema = {
  type: 'object',
  additionalProperties: false,
  required: [
    'recognitionStatus',
    'sourceType',
    'trainNumber',
    'fromStation',
    'fromStationEnglish',
    'toStation',
    'toStationEnglish',
    'departureDate',
    'departureTime',
    'arrivalDate',
    'arrivalTime',
    'carriage',
    'seat',
    'seatClass',
    'passengerName',
    'boardingGate',
    'boardingGateEnglish',
    'waitingHall',
    'waitingHallEnglish',
    'platform',
    'platformEnglish',
    'gate',
    'gateEnglish',
    'checkIn',
    'checkInEnglish',
    'coach',
    'ticketNumber',
    'orderNumber',
    'notes',
    'confidence',
    'needsManualCheck',
  ],
  properties: {
    recognitionStatus: { type: 'string', enum: ['recognized', 'uncertain', 'unable_to_recognize'] },
    sourceType: { type: 'string', enum: ['12306', 'trip_com', 'china_railway_e_ticket', 'order_screenshot', 'unknown'] },
    trainNumber: { type: 'string' },
    fromStation: { type: 'string' },
    fromStationEnglish: { type: 'string' },
    toStation: { type: 'string' },
    toStationEnglish: { type: 'string' },
    departureDate: { type: 'string' },
    departureTime: { type: 'string' },
    arrivalDate: { type: 'string' },
    arrivalTime: { type: 'string' },
    carriage: { type: 'string' },
    seat: { type: 'string' },
    seatClass: { type: 'string' },
    passengerName: { type: 'string' },
    boardingGate: { type: 'string' },
    boardingGateEnglish: { type: 'string' },
    waitingHall: { type: 'string' },
    waitingHallEnglish: { type: 'string' },
    platform: { type: 'string' },
    platformEnglish: { type: 'string' },
    gate: { type: 'string' },
    gateEnglish: { type: 'string' },
    checkIn: { type: 'string' },
    checkInEnglish: { type: 'string' },
    coach: { type: 'string' },
    ticketNumber: { type: 'string' },
    orderNumber: { type: 'string' },
    notes: { type: 'array', items: { type: 'string' } },
    confidence: { type: 'string', enum: ['high', 'medium', 'low'] },
    needsManualCheck: { type: 'boolean' },
  },
} as const;
